# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400)),
                ('genero', models.CharField(choices=[('Humor', 'Humor'), ('Comedia', 'Comedia')], max_length=10, verbose_name='Genero')),
                ('fecha_estreno', models.DateTimeField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Director')),
            ],
        ),
    ]
