# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(choices=[('ATP', 'ATP'), ('+13', '+13'), ('+16', '+16'), ('+18', '+18')], default=12, max_length=3, verbose_name='Edades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(default=32, upload_to=b''),
            preserve_default=False,
        ),
    ]
