# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190613_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Accion', 'Accion'), ('Ciencia Ficcion', 'Ciencia Ficcion'), ('Terror', 'Terror'), ('Aventura', 'Aventura'), ('Policial', 'Policial'), ('Politica', 'Politica'), ('Fantasia', 'Fantasia')], max_length=10, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
