# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190613_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar_sala',
            name='en_cartelera',
            field=models.BooleanField(default=True),
        ),
    ]
