# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_asignar_sala_en_cartelera'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='precio',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
