# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_entrada_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sala'),
        ),
    ]
