# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_entrada_pelicula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='sala',
        ),
        migrations.AddField(
            model_name='entrada',
            name='sala_p',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.asignar_Sala'),
            preserve_default=False,
        ),
    ]
