# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190617_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar_sala',
            name='entradas_vendidas',
            field=models.IntegerField(default=0),
        ),
    ]
